@url = http://localhost:3000


### Registro de Nuevo Usuario
# @name register
POST {{url}}/usuarios
Content-Type: application/json

{
    "username": "asdr",
    "email": "juanxd@ejemplo.com",
    "password": "hola1234"
}

### Login de Usuario
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "juanxd@ejemplo.com",
    "password": "hola1234"
}

###
# Guarda el token de la respuesta de login
@token = {{login.response.body.token}}


### Consultar todos los usuarios (protegido)
GET {{url}}/usuarios
Authorization: Bearer {{token}}

### Consultar por un usuario (protegido)
GET {{url}}/usuarios/1
Authorization: Bearer {{token}}

### Actualizar un usuario (protegido)
PUT {{url}}/usuarios/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "ajskajskjaks",
    "email": "twister@ejemplo.com"
}

### Eliminar un usuario (protegido)
DELETE {{url}}/usuarios/1
Authorization: Bearer {{token}}